In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv(r"C:\Users\ADITYA GUPTA\Downloads\Data\messy_customer_dataset.csv")
df

,customer_id,name,email,age,city,signup_date,purchase_amount
0,101.0,Aditya,aditya@gmail.com,23.0,Delhi,2024-01-05,2500.0
1,102.0,Rohit,rohit@gmail.com,25.0,Mumbai,05-02-2024,3200.0
2,103.0,Sonia,sonia@gmail.com,NaN,Delhi,2024/03/10,1800.0
3,104.0,Rahul,rahul@gmail.com,29.0,mumbai,2024-04-12,NaN
4,105.0,Priya,priya@gmail.com,22.0,Bangalore,12-05-2024,1500.0
5,105.0,Priya,priya@gmail.com,22.0,Bangalore,12-05-2024,1500.0
6,107.0,Aman,aman@gmail.com,200.0,Delhi,2024-06-01,99999.0
7,108.0,Neha,neha@gmail.com,27.0,Pune,2024-07-15,2100.0
8,NaN,Karan,karan@gmail,24.0,Pune,2024/08/20,1900.0
9,110.0,Riya,riya@gmail.com,-5.0,Delhi,2024-09-10,2000.0
10,111.0,Vikas,NaN,30.0,Mumbai,2024-10-05,1750.0
11,112.0,Anjali,anjali@gmail.com,28.0,bangalore,15-11-2024,1600.0

In [ ]:
df["signup_date"] = pd.to_datetime(df["signup_date"], format='mixed', dayfirst=True).apply(lambda x: x if pd.notna(x) else pd.to_datetime("2024-01-01"))
df

,customer_id,name,email,age,city,signup_date,purchase_amount
0,101.0,Aditya,aditya@gmail.com,23.0,Delhi,2024-05-01,2500.0
1,102.0,Rohit,rohit@gmail.com,25.0,Mumbai,2024-02-05,3200.0
2,103.0,Sonia,sonia@gmail.com,NaN,Delhi,2024-10-03,1800.0
3,104.0,Rahul,rahul@gmail.com,29.0,mumbai,2024-12-04,NaN
4,105.0,Priya,priya@gmail.com,22.0,Bangalore,2024-05-12,1500.0
5,105.0,Priya,priya@gmail.com,22.0,Bangalore,2024-05-12,1500.0
6,107.0,Aman,aman@gmail.com,200.0,Delhi,2024-01-06,99999.0
7,108.0,Neha,neha@gmail.com,27.0,Pune,2024-07-15,2100.0
8,NaN,Karan,karan@gmail,24.0,Pune,2024-08-20,1900.0
9,110.0,Riya,riya@gmail.com,-5.0,Delhi,2024-10-09,2000.0
10,111.0,Vikas,NaN,30.0,Mumbai,2024-05-10,1750.0
11,112.0,Anjali,anjali@gmail.com,28.0,bangalore,2024-11-15,1600.0

In [ ]:
df['customer_id'] = df['customer_id'].astype(float)
df

,customer_id,name,email,age,city,signup_date,purchase_amount
0,101.0,Aditya,aditya@gmail.com,23.0,Delhi,2024-05-01,2500.0
1,102.0,Rohit,rohit@gmail.com,25.0,Mumbai,2024-02-05,3200.0
2,103.0,Sonia,sonia@gmail.com,NaN,Delhi,2024-10-03,1800.0
3,104.0,Rahul,rahul@gmail.com,29.0,mumbai,2024-12-04,NaN
4,105.0,Priya,priya@gmail.com,22.0,Bangalore,2024-05-12,1500.0
5,105.0,Priya,priya@gmail.com,22.0,Bangalore,2024-05-12,1500.0
6,107.0,Aman,aman@gmail.com,200.0,Delhi,2024-01-06,99999.0
7,108.0,Neha,neha@gmail.com,27.0,Pune,2024-07-15,2100.0
8,NaN,Karan,karan@gmail,24.0,Pune,2024-08-20,1900.0
9,110.0,Riya,riya@gmail.com,-5.0,Delhi,2024-10-09,2000.0
10,111.0,Vikas,NaN,30.0,Mumbai,2024-05-10,1750.0
11,112.0,Anjali,anjali@gmail.com,28.0,bangalore,2024-11-15,1600.0

In [ ]:
df['customer_id'] = df['customer_id'].interpolate()
df

,customer_id,name,email,age,city,signup_date,purchase_amount
0,101.0,Aditya,aditya@gmail.com,23.0,Delhi,2024-05-01,2500.0
1,102.0,Rohit,rohit@gmail.com,25.0,Mumbai,2024-02-05,3200.0
2,103.0,Sonia,sonia@gmail.com,NaN,Delhi,2024-10-03,1800.0
3,104.0,Rahul,rahul@gmail.com,29.0,mumbai,2024-12-04,NaN
4,105.0,Priya,priya@gmail.com,22.0,Bangalore,2024-05-12,1500.0
5,105.0,Priya,priya@gmail.com,22.0,Bangalore,2024-05-12,1500.0
6,107.0,Aman,aman@gmail.com,200.0,Delhi,2024-01-06,99999.0
7,108.0,Neha,neha@gmail.com,27.0,Pune,2024-07-15,2100.0
8,109.0,Karan,karan@gmail,24.0,Pune,2024-08-20,1900.0
9,110.0,Riya,riya@gmail.com,-5.0,Delhi,2024-10-09,2000.0
10,111.0,Vikas,NaN,30.0,Mumbai,2024-05-10,1750.0
11,112.0,Anjali,anjali@gmail.com,28.0,bangalore,2024-11-15,1600.0

In [ ]:
df['email'] = df['email'].fillna('provided@gmail.com')
df

,customer_id,name,email,age,city,signup_date,purchase_amount
0,101.0,Aditya,aditya@gmail.com,23.0,Delhi,2024-05-01,2500.0
1,102.0,Rohit,rohit@gmail.com,25.0,Mumbai,2024-02-05,3200.0
2,103.0,Sonia,sonia@gmail.com,NaN,Delhi,2024-10-03,1800.0
3,104.0,Rahul,rahul@gmail.com,29.0,mumbai,2024-12-04,NaN
4,105.0,Priya,priya@gmail.com,22.0,Bangalore,2024-05-12,1500.0
5,105.0,Priya,priya@gmail.com,22.0,Bangalore,2024-05-12,1500.0
6,107.0,Aman,aman@gmail.com,200.0,Delhi,2024-01-06,99999.0
7,108.0,Neha,neha@gmail.com,27.0,Pune,2024-07-15,2100.0
8,109.0,Karan,karan@gmail,24.0,Pune,2024-08-20,1900.0
9,110.0,Riya,riya@gmail.com,-5.0,Delhi,2024-10-09,2000.0
10,111.0,Vikas,provided@gmail.com,30.0,Mumbai,2024-05-10,1750.0
11,112.0,Anjali,anjali@gmail.com,28.0,bangalore,2024-11-15,1600.0

In [ ]:
df['customer_id'] = df['customer_id'].astype(int)
df

,customer_id,name,email,age,city,signup_date,purchase_amount
0,101,Aditya,aditya@gmail.com,23.0,Delhi,2024-05-01,2500.0
1,102,Rohit,rohit@gmail.com,25.0,Mumbai,2024-02-05,3200.0
2,103,Sonia,sonia@gmail.com,NaN,Delhi,2024-10-03,1800.0
3,104,Rahul,rahul@gmail.com,29.0,mumbai,2024-12-04,NaN
4,105,Priya,priya@gmail.com,22.0,Bangalore,2024-05-12,1500.0
5,105,Priya,priya@gmail.com,22.0,Bangalore,2024-05-12,1500.0
6,107,Aman,aman@gmail.com,200.0,Delhi,2024-01-06,99999.0
7,108,Neha,neha@gmail.com,27.0,Pune,2024-07-15,2100.0
8,109,Karan,karan@gmail,24.0,Pune,2024-08-20,1900.0
9,110,Riya,riya@gmail.com,-5.0,Delhi,2024-10-09,2000.0
10,111,Vikas,provided@gmail.com,30.0,Mumbai,2024-05-10,1750.0
11,112,Anjali,anjali@gmail.com,28.0,bangalore,2024-11-15,1600.0

In [ ]:
df['age'] = df['age'].fillna(df['age'].median())
df

,customer_id,name,email,age,city,signup_date,purchase_amount
0,101,Aditya,aditya@gmail.com,23.0,Delhi,2024-05-01,2500.0
1,102,Rohit,rohit@gmail.com,25.0,Mumbai,2024-02-05,3200.0
2,103,Sonia,sonia@gmail.com,25.0,Delhi,2024-10-03,1800.0
3,104,Rahul,rahul@gmail.com,29.0,mumbai,2024-12-04,NaN
4,105,Priya,priya@gmail.com,22.0,Bangalore,2024-05-12,1500.0
5,105,Priya,priya@gmail.com,22.0,Bangalore,2024-05-12,1500.0
6,107,Aman,aman@gmail.com,200.0,Delhi,2024-01-06,99999.0
7,108,Neha,neha@gmail.com,27.0,Pune,2024-07-15,2100.0
8,109,Karan,karan@gmail,24.0,Pune,2024-08-20,1900.0
9,110,Riya,riya@gmail.com,-5.0,Delhi,2024-10-09,2000.0
10,111,Vikas,provided@gmail.com,30.0,Mumbai,2024-05-10,1750.0
11,112,Anjali,anjali@gmail.com,28.0,bangalore,2024-11-15,1600.0

In [ ]:
df.loc[6, 'age'] = 27
df

,customer_id,name,email,age,city,signup_date,purchase_amount
0,101,Aditya,aditya@gmail.com,23.0,Delhi,2024-05-01,2500.0
1,102,Rohit,rohit@gmail.com,25.0,Mumbai,2024-02-05,3200.0
2,103,Sonia,sonia@gmail.com,25.0,Delhi,2024-10-03,1800.0
3,104,Rahul,rahul@gmail.com,29.0,mumbai,2024-12-04,NaN
4,105,Priya,priya@gmail.com,22.0,Bangalore,2024-05-12,1500.0
5,105,Priya,priya@gmail.com,22.0,Bangalore,2024-05-12,1500.0
6,107,Aman,aman@gmail.com,27.0,Delhi,2024-01-06,99999.0
7,108,Neha,neha@gmail.com,27.0,Pune,2024-07-15,2100.0
8,109,Karan,karan@gmail,24.0,Pune,2024-08-20,1900.0
9,110,Riya,riya@gmail.com,-5.0,Delhi,2024-10-09,2000.0
10,111,Vikas,provided@gmail.com,30.0,Mumbai,2024-05-10,1750.0
11,112,Anjali,anjali@gmail.com,28.0,bangalore,2024-11-15,1600.0

In [ ]:
df.loc[9, 'age'] = 27
df

,customer_id,name,email,age,city,signup_date,purchase_amount
0,101,Aditya,aditya@gmail.com,23.0,Delhi,2024-05-01,2500.0
1,102,Rohit,rohit@gmail.com,25.0,Mumbai,2024-02-05,3200.0
2,103,Sonia,sonia@gmail.com,25.0,Delhi,2024-10-03,1800.0
3,104,Rahul,rahul@gmail.com,29.0,mumbai,2024-12-04,NaN
4,105,Priya,priya@gmail.com,22.0,Bangalore,2024-05-12,1500.0
5,105,Priya,priya@gmail.com,22.0,Bangalore,2024-05-12,1500.0
6,107,Aman,aman@gmail.com,27.0,Delhi,2024-01-06,99999.0
7,108,Neha,neha@gmail.com,27.0,Pune,2024-07-15,2100.0
8,109,Karan,karan@gmail,24.0,Pune,2024-08-20,1900.0
9,110,Riya,riya@gmail.com,27.0,Delhi,2024-10-09,2000.0
10,111,Vikas,provided@gmail.com,30.0,Mumbai,2024-05-10,1750.0
11,112,Anjali,anjali@gmail.com,28.0,bangalore,2024-11-15,1600.0

In [ ]:
df['age'] = df['age'].astype(int)
df

,customer_id,name,email,age,city,signup_date,purchase_amount
0,101,Aditya,aditya@gmail.com,23,Delhi,2024-05-01,2500.0
1,102,Rohit,rohit@gmail.com,25,Mumbai,2024-02-05,3200.0
2,103,Sonia,sonia@gmail.com,25,Delhi,2024-10-03,1800.0
3,104,Rahul,rahul@gmail.com,29,mumbai,2024-12-04,NaN
4,105,Priya,priya@gmail.com,22,Bangalore,2024-05-12,1500.0
5,105,Priya,priya@gmail.com,22,Bangalore,2024-05-12,1500.0
6,107,Aman,aman@gmail.com,27,Delhi,2024-01-06,99999.0
7,108,Neha,neha@gmail.com,27,Pune,2024-07-15,2100.0
8,109,Karan,karan@gmail,24,Pune,2024-08-20,1900.0
9,110,Riya,riya@gmail.com,27,Delhi,2024-10-09,2000.0
10,111,Vikas,provided@gmail.com,30,Mumbai,2024-05-10,1750.0
11,112,Anjali,anjali@gmail.com,28,bangalore,2024-11-15,1600.0

In [ ]:
df['purchase_amount'] = df['purchase_amount'].fillna(df['purchase_amount'].mean())
df

,customer_id,name,email,age,city,signup_date,purchase_amount
0,101,Aditya,aditya@gmail.com,23,Delhi,2024-05-01,2500.000000
1,102,Rohit,rohit@gmail.com,25,Mumbai,2024-02-05,3200.000000
2,103,Sonia,sonia@gmail.com,25,Delhi,2024-10-03,1800.000000
3,104,Rahul,rahul@gmail.com,29,mumbai,2024-12-04,10895.363636
4,105,Priya,priya@gmail.com,22,Bangalore,2024-05-12,1500.000000
5,105,Priya,priya@gmail.com,22,Bangalore,2024-05-12,1500.000000
6,107,Aman,aman@gmail.com,27,Delhi,2024-01-06,99999.000000
7,108,Neha,neha@gmail.com,27,Pune,2024-07-15,2100.000000
8,109,Karan,karan@gmail,24,Pune,2024-08-20,1900.000000
9,110,Riya,riya@gmail.com,27,Delhi,2024-10-09,2000.000000
10,111,Vikas,provided@gmail.com,30,Mumbai,2024-05-10,1750.000000
11,112,Anjali,anjali@gmail.com,28,bangalore,2024-11-15,1600.000000

In [ ]:
df['purchase_amount'] = df['purchase_amount'].astype(int)
df

,customer_id,name,email,age,city,signup_date,purchase_amount
0,101,Aditya,aditya@gmail.com,23,Delhi,2024-05-01,2500
1,102,Rohit,rohit@gmail.com,25,Mumbai,2024-02-05,3200
2,103,Sonia,sonia@gmail.com,25,Delhi,2024-10-03,1800
3,104,Rahul,rahul@gmail.com,29,mumbai,2024-12-04,10895
4,105,Priya,priya@gmail.com,22,Bangalore,2024-05-12,1500
5,105,Priya,priya@gmail.com,22,Bangalore,2024-05-12,1500
6,107,Aman,aman@gmail.com,27,Delhi,2024-01-06,99999
7,108,Neha,neha@gmail.com,27,Pune,2024-07-15,2100
8,109,Karan,karan@gmail,24,Pune,2024-08-20,1900
9,110,Riya,riya@gmail.com,27,Delhi,2024-10-09,2000
10,111,Vikas,provided@gmail.com,30,Mumbai,2024-05-10,1750
11,112,Anjali,anjali@gmail.com,28,bangalore,2024-11-15,1600

In [ ]:
df.loc[6, 'purchase_amount'] = 4327
df

,customer_id,name,email,age,city,signup_date,purchase_amount
0,101,Aditya,aditya@gmail.com,23,Delhi,2024-05-01,2500
1,102,Rohit,rohit@gmail.com,25,Mumbai,2024-02-05,3200
2,103,Sonia,sonia@gmail.com,25,Delhi,2024-10-03,1800
3,104,Rahul,rahul@gmail.com,29,mumbai,2024-12-04,10895
4,105,Priya,priya@gmail.com,22,Bangalore,2024-05-12,1500
5,105,Priya,priya@gmail.com,22,Bangalore,2024-05-12,1500
6,107,Aman,aman@gmail.com,27,Delhi,2024-01-06,4327
7,108,Neha,neha@gmail.com,27,Pune,2024-07-15,2100
8,109,Karan,karan@gmail,24,Pune,2024-08-20,1900
9,110,Riya,riya@gmail.com,27,Delhi,2024-10-09,2000
10,111,Vikas,provided@gmail.com,30,Mumbai,2024-05-10,1750
11,112,Anjali,anjali@gmail.com,28,bangalore,2024-11-15,1600

In [ ]:
df.drop_duplicates(inplace=True)
df

,customer_id,name,email,age,city,signup_date,purchase_amount
0,101,Aditya,aditya@gmail.com,23,Delhi,2024-05-01,2500
1,102,Rohit,rohit@gmail.com,25,Mumbai,2024-02-05,3200
2,103,Sonia,sonia@gmail.com,25,Delhi,2024-10-03,1800
3,104,Rahul,rahul@gmail.com,29,mumbai,2024-12-04,10895
4,105,Priya,priya@gmail.com,22,Bangalore,2024-05-12,1500
6,107,Aman,aman@gmail.com,27,Delhi,2024-01-06,4327
7,108,Neha,neha@gmail.com,27,Pune,2024-07-15,2100
8,109,Karan,karan@gmail,24,Pune,2024-08-20,1900
9,110,Riya,riya@gmail.com,27,Delhi,2024-10-09,2000
10,111,Vikas,provided@gmail.com,30,Mumbai,2024-05-10,1750
11,112,Anjali,anjali@gmail.com,28,bangalore,2024-11-15,1600

In [ ]:
df.shape

(11, 7)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
Index: 11 entries, 0 to 11
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      11 non-null     int64
 1   name             11 non-null     str
 2   email            11 non-null     str
 3   age              11 non-null     int64
 4   city             11 non-null     str
 5   signup_date      11 non-null     datetime64[us]
 6   purchase_amount  11 non-null     int64
dtypes: datetime64[us](1), int64(3), str(3)
memory usage: 704.0 bytes

In [ ]:
df.describe()

       customer_id        age                 signup_date  purchase_amount
count    11.000000  11.000000                          11        11.000000
mean    106.545455  26.090909  2024-07-06 19:38:10.909091      3052.000000
min     101.000000  22.000000         2024-01-06 00:00:00      1500.000000
25%     103.500000  24.500000         2024-05-05 12:00:00      1775.000000
50%     107.000000  27.000000         2024-07-15 00:00:00      2000.000000
75%     109.500000  27.500000         2024-10-06 00:00:00      2850.000000
max     112.000000  30.000000         2024-12-04 00:00:00     10895.000000
std       3.777926   2.508168                         NaN      2731.020139

In [ ]:
df.isnull().sum()

customer_id        0
name               0
email              0
age                0
city               0
signup_date        0
purchase_amount    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.rename(columns = {'name' : 'first_name'}, inplace = True)
df

,customer_id,first_name,email,age,city,signup_date,purchase_amount
0,101,Aditya,aditya@gmail.com,23,Delhi,2024-05-01,2500
1,102,Rohit,rohit@gmail.com,25,Mumbai,2024-02-05,3200
2,103,Sonia,sonia@gmail.com,25,Delhi,2024-10-03,1800
3,104,Rahul,rahul@gmail.com,29,mumbai,2024-12-04,10895
4,105,Priya,priya@gmail.com,22,Bangalore,2024-05-12,1500
6,107,Aman,aman@gmail.com,27,Delhi,2024-01-06,4327
7,108,Neha,neha@gmail.com,27,Pune,2024-07-15,2100
8,109,Karan,karan@gmail,24,Pune,2024-08-20,1900
9,110,Riya,riya@gmail.com,27,Delhi,2024-10-09,2000
10,111,Vikas,provided@gmail.com,30,Mumbai,2024-05-10,1750
11,112,Anjali,anjali@gmail.com,28,bangalore,2024-11-15,1600

In [ ]:
df.describe()

       customer_id        age                 signup_date  purchase_amount
count    11.000000  11.000000                          11        11.000000
mean    106.545455  26.090909  2024-07-06 19:38:10.909091      3052.000000
min     101.000000  22.000000         2024-01-06 00:00:00      1500.000000
25%     103.500000  24.500000         2024-05-05 12:00:00      1775.000000
50%     107.000000  27.000000         2024-07-15 00:00:00      2000.000000
75%     109.500000  27.500000         2024-10-06 00:00:00      2850.000000
max     112.000000  30.000000         2024-12-04 00:00:00     10895.000000
std       3.777926   2.508168                         NaN      2731.020139

In [ ]:
df.describe(include='object')

C:\Users\ADITYA GUPTA\AppData\Local\Temp\ipykernel_1592\87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

       first_name             email   city
count          11                11     11
unique         11                11      6
top        Aditya  aditya@gmail.com  Delhi
freq            1                 1      4

In [ ]:
df.info()

<class 'pandas.DataFrame'>
Index: 11 entries, 0 to 11
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      11 non-null     int64
 1   first_name       11 non-null     str
 2   email            11 non-null     str
 3   age              11 non-null     int64
 4   city             11 non-null     str
 5   signup_date      11 non-null     datetime64[us]
 6   purchase_amount  11 non-null     int64
dtypes: datetime64[us](1), int64(3), str(3)
memory usage: 704.0 bytes